# Generated by Django 5.2 on 2025-12-29 07:38

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "member_number",
                    models.CharField(
                        help_text="Unique member number within this SACCO",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        help_text="National ID, passport, or other government ID number",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL_ID", "National ID"),
                            ("PASSPORT", "Passport"),
                            ("DRIVERS_LICENSE", "Driver's License"),
                            ("VOTER_ID", "Voter ID"),
                            ("OTHER", "Other"),
                        ],
                        default="NATIONAL_ID",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MR", "Mr."),
                            ("MRS", "Mrs."),
                            ("MS", "Ms."),
                            ("DR", "Dr."),
                            ("PROF", "Prof."),
                            ("HON", "Hon."),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Legal first name as per ID document", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Legal last name as per ID document", max_length=100
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Legal middle name as per ID document",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(help_text="Date of birth as per ID document"),
                ),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=20
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                            ("SEPARATED", "Separated"),
                            ("COHABITING", "Cohabiting"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "nationality",
                    django_countries.fields.CountryField(default="UG", max_length=2),
                ),
                (
                    "religious_affiliation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("catholic", "Catholic"),
                            ("protestant", "Protestant"),
                            ("anglican", "Anglican"),
                            ("baptist", "Baptist"),
                            ("pentecostal", "Pentecostal"),
                            ("evangelical", "Evangelical"),
                            ("adventist", "Adventist"),
                            ("islam", "Islam"),
                            ("hindu", "Hindu"),
                            ("buddhist", "Buddhist"),
                            ("jewish", "Jewish"),
                            ("traditional", "Traditional"),
                            ("none", "No Religion"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Religious Affiliation",
                    ),
                ),
                (
                    "member_category",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Member"),
                            ("PREMIUM", "Premium Member"),
                            ("SENIOR", "Senior Member"),
                            ("YOUTH", "Youth Member"),
                            ("BUSINESS", "Business Member"),
                            ("VIP", "VIP Member"),
                            ("STUDENT", "Student Member"),
                            ("PENSIONER", "Pensioner Member"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                (
                    "membership_plan",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic Plan"),
                            ("STANDARD", "Standard Plan"),
                            ("PREMIUM", "Premium Plan"),
                            ("CORPORATE", "Corporate Plan"),
                            ("ENTERPRISE", "Enterprise Plan"),
                            ("FAMILY", "Family Plan"),
                            ("STUDENT", "Student Plan"),
                        ],
                        default="BASIC",
                        max_length=20,
                    ),
                ),
                (
                    "membership_date",
                    models.DateField(help_text="Date when member joined the SACCO"),
                ),
                (
                    "membership_application_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when membership application was submitted",
                        null=True,
                    ),
                ),
                (
                    "membership_approved_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when membership was approved",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("DORMANT", "Dormant"),
                            ("SUSPENDED", "Suspended"),
                            ("ON_HOLD", "On Hold"),
                            ("BLACKLISTED", "Blacklisted"),
                            ("DECEASED", "Deceased"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("GRADUATED", "Graduated to Higher Tier"),
                            ("DELINQUENT", "Delinquent"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="PENDING_APPROVAL",
                        max_length=20,
                    ),
                ),
                ("status_changed_date", models.DateTimeField(auto_now_add=True)),
                ("status_changed_reason", models.TextField(blank=True, null=True)),
                (
                    "maximum_loan_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.0"),
                        help_text="Maximum loan as multiple of savings balance",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "loan_interest_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        help_text="Interest rate discount percentage for this member",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "special_privileges",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Special privileges or benefits for this member",
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("employer", models.CharField(blank=True, max_length=200, null=True)),
                ("employer_address", models.TextField(blank=True, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("EMPLOYED", "Employed"),
                            ("SELF_EMPLOYED", "Self-Employed"),
                            ("UNEMPLOYED", "Unemployed"),
                            ("STUDENT", "Student"),
                            ("RETIRED", "Retired"),
                            ("HOUSEWIFE", "Housewife/Househusband"),
                            ("CASUAL_WORKER", "Casual Worker"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated monthly income",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "income_source",
                    models.CharField(
                        blank=True,
                        help_text="Primary source of income",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "other_income_sources",
                    models.TextField(
                        blank=True, help_text="Other sources of income", null=True
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary email for official correspondence",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        help_text="Primary phone number for official contact",
                        max_length=20,
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        help_text="Current residential address for official records"
                    ),
                ),
                (
                    "postal_address",
                    models.CharField(
                        blank=True,
                        help_text="Postal address for correspondence",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(default="UG", max_length=2),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax identification number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tax_exemption_status",
                    models.BooleanField(
                        default=False, help_text="Whether member is exempt from taxes"
                    ),
                ),
                (
                    "tax_exemption_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for tax exemption",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("IN_PROGRESS", "In Progress"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("REQUIRES_UPDATE", "Requires Update"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("kyc_verified_date", models.DateTimeField(blank=True, null=True)),
                ("kyc_expiry_date", models.DateTimeField(blank=True, null=True)),
                ("kyc_documents_uploaded", models.BooleanField(default=False)),
                ("kyc_notes", models.TextField(blank=True, null=True)),
                (
                    "credit_score",
                    models.IntegerField(
                        default=500,
                        help_text="Credit score range: 0-1000",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "risk_rating",
                    models.CharField(
                        choices=[
                            ("VERY_LOW", "Very Low Risk"),
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("VERY_HIGH", "Very High Risk"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("risk_assessment_date", models.DateTimeField(blank=True, null=True)),
                ("risk_assessment_notes", models.TextField(blank=True, null=True)),
                (
                    "member_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Member's photograph",
                        null=True,
                        upload_to="members/photos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "db_table": "members",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member_number"], name="members_member__6c837a_idx"
                    ),
                    models.Index(
                        fields=["id_number"], name="members_id_numb_614b67_idx"
                    ),
                    models.Index(fields=["status"], name="members_status_e4ea77_idx"),
                    models.Index(
                        fields=["member_category"], name="members_member__a37257_idx"
                    ),
                    models.Index(
                        fields=["membership_date"], name="members_members_b83330_idx"
                    ),
                    models.Index(
                        fields=["kyc_status"], name="members_kyc_sta_e730e4_idx"
                    ),
                    models.Index(
                        fields=["risk_rating"], name="members_risk_ra_0c3fee_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="members_created_1df6fe_idx"
                    ),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="members_first_n_ae9002_idx",
                    ),
                    models.Index(
                        fields=["phone_primary"], name="members_phone_p_8e2a39_idx"
                    ),
                    models.Index(
                        fields=["personal_email"], name="members_persona_4bdade_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("credit_score__gte", 0), ("credit_score__lte", 1000)
                        ),
                        name="valid_credit_score",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("maximum_loan_multiplier__gte", 0),
                            ("maximum_loan_multiplier__lte", 20),
                        ),
                        name="valid_loan_multiplier",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MEMBER", "Member"),
                            ("LEADER", "Leader"),
                            ("SECRETARY", "Secretary"),
                            ("TREASURER", "Treasurer"),
                            ("COMMITTEE_MEMBER", "Committee Member"),
                            ("COORDINATOR", "Coordinator"),
                            ("MENTOR", "Mentor"),
                        ],
                        default="MEMBER",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                ("join_date", models.DateField(verbose_name="Join Date")),
                (
                    "exit_date",
                    models.DateField(blank=True, null=True, verbose_name="Exit Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("RESIGNED", "Resigned"),
                            ("EXPELLED", "Expelled"),
                            ("ON_LEAVE", "On Leave"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "monthly_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly contribution amount",
                        max_digits=10,
                        verbose_name="Monthly Contribution",
                    ),
                ),
                (
                    "total_contributions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount contributed to this group",
                        max_digits=12,
                        verbose_name="Total Contributions",
                    ),
                ),
                (
                    "meeting_attendance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of meetings attended",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Meeting Attendance Rate",
                    ),
                ),
                (
                    "last_meeting_attended",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Meeting Attended"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "exit_reason",
                    models.TextField(blank=True, null=True, verbose_name="Exit Reason"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.member"
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Membership",
                "verbose_name_plural": "Group Memberships",
                "db_table": "member_group_memberships",
                "ordering": ["-is_active", "-join_date"],
            },
        ),
        migrations.CreateModel(
            name="MemberGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Group Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("LENDING_CIRCLE", "Lending Circle"),
                            ("SAVINGS_GROUP", "Savings Group"),
                            ("COMMITTEE", "Committee"),
                            ("SPECIAL_INTEREST", "Special Interest Group"),
                            ("PROJECT_GROUP", "Project Group"),
                            ("INVESTMENT_CLUB", "Investment Club"),
                            ("TRAINING_GROUP", "Training Group"),
                            ("OTHER", "Other"),
                        ],
                        default="LENDING_CIRCLE",
                        max_length=20,
                        verbose_name="Group Type",
                    ),
                ),
                ("formation_date", models.DateField(verbose_name="Formation Date")),
                (
                    "meeting_frequency",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("BI_WEEKLY", "Bi-weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("AS_NEEDED", "As Needed"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="Meeting Frequency",
                    ),
                ),
                (
                    "meeting_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Meeting Day",
                    ),
                ),
                (
                    "meeting_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Meeting Time"
                    ),
                ),
                (
                    "meeting_location",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Meeting Location",
                    ),
                ),
                (
                    "minimum_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum monthly contribution",
                        max_digits=10,
                        verbose_name="Minimum Contribution",
                    ),
                ),
                (
                    "maximum_loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum loan amount for group members",
                        max_digits=12,
                        verbose_name="Maximum Loan Amount",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly interest rate percentage",
                        max_digits=5,
                        verbose_name="Interest Rate",
                    ),
                ),
                (
                    "maximum_members",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum number of members allowed",
                        verbose_name="Maximum Members",
                    ),
                ),
                (
                    "minimum_members",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minimum number of members required",
                        verbose_name="Minimum Members",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("is_full", models.BooleanField(default=False, verbose_name="Full")),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Terms and Conditions"
                    ),
                ),
                (
                    "group_rules",
                    models.TextField(blank=True, null=True, verbose_name="Group Rules"),
                ),
                (
                    "group_leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_groups",
                        to="members.member",
                        verbose_name="Group Leader",
                    ),
                ),
                (
                    "group_secretary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secretary_of_groups",
                        to="members.member",
                        verbose_name="Group Secretary",
                    ),
                ),
                (
                    "group_treasurer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treasurer_of_groups",
                        to="members.member",
                        verbose_name="Group Treasurer",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="member_groups",
                        through="members.GroupMembership",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Group",
                "verbose_name_plural": "Member Groups",
                "db_table": "member_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.membergroup"
            ),
        ),
        migrations.CreateModel(
            name="MemberPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("BANK_ACCOUNT", "Bank Account"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                        ],
                        max_length=20,
                        verbose_name="Method Type",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Bank name or mobile money provider",
                        max_length=100,
                        verbose_name="Provider/Bank Name",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Account number or mobile money number",
                        max_length=50,
                        verbose_name="Account/Phone Number",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="Name as registered on account",
                        max_length=100,
                        verbose_name="Account Name",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAVINGS", "Savings Account"),
                            ("CHECKING", "Checking Account"),
                            ("CURRENT", "Current Account"),
                            ("FIXED_DEPOSIT", "Fixed Deposit"),
                        ],
                        help_text="For bank accounts only",
                        max_length=20,
                        null=True,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        help_text="Bank branch or mobile money agent location",
                        max_length=100,
                        null=True,
                        verbose_name="Branch/Location",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary payment method for this member",
                        verbose_name="Primary Method",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this payment method has been verified",
                        verbose_name="Verified",
                    ),
                ),
                (
                    "verified_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this payment method is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="members.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "member_payment_methods",
                "ordering": ["-is_primary", "-is_verified", "provider"],
            },
        ),
        migrations.CreateModel(
            name="NextOfKin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of next of kin",
                        max_length=100,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("SPOUSE", "Spouse"),
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("SON", "Son"),
                            ("DAUGHTER", "Daughter"),
                            ("BROTHER", "Brother"),
                            ("SISTER", "Sister"),
                            ("UNCLE", "Uncle"),
                            ("AUNT", "Aunt"),
                            ("NEPHEW", "Nephew"),
                            ("NIECE", "Niece"),
                            ("GRANDPARENT", "Grandparent"),
                            ("GRANDCHILD", "Grandchild"),
                            ("COUSIN", "Cousin"),
                            ("GUARDIAN", "Guardian"),
                            ("FRIEND", "Friend"),
                            ("PARTNER", "Partner"),
                            ("IN_LAW", "In-law"),
                            ("COLLEAGUE", "Colleague"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Relationship to member",
                        max_length=50,
                        verbose_name="Relationship",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        help_text="Primary phone number",
                        max_length=15,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address",
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Residential address",
                        null=True,
                        verbose_name="Physical Address",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="National ID or other identification number",
                        max_length=30,
                        null=True,
                        verbose_name="ID Number",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Date of birth",
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary next of kin",
                        verbose_name="Primary Next of Kin",
                    ),
                ),
                (
                    "is_emergency_contact",
                    models.BooleanField(
                        default=False,
                        help_text="Can be contacted in case of emergency",
                        verbose_name="Emergency Contact",
                    ),
                ),
                (
                    "is_beneficiary",
                    models.BooleanField(
                        default=False,
                        help_text="Beneficiary of member's estate/benefits",
                        verbose_name="Beneficiary",
                    ),
                ),
                (
                    "beneficiary_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of benefits allocated to this next of kin",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Beneficiary Percentage",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_of_kin",
                        to="members.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Next of Kin",
                "verbose_name_plural": "Next of Kin",
                "db_table": "member_next_of_kin",
                "ordering": ["-is_primary", "-is_emergency_contact", "name"],
            },
        ),
        migrations.CreateModel(
            name="MemberAdditionalContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("WORK_EMAIL", "Work Email"),
                            ("ALTERNATE_EMAIL", "Alternate Email"),
                            ("SECONDARY_PHONE", "Secondary Phone"),
                            ("WORK_PHONE", "Work Phone"),
                            ("FAX", "Fax"),
                            ("WHATSAPP", "WhatsApp"),
                            ("TELEGRAM", "Telegram"),
                        ],
                        max_length=20,
                        verbose_name="Contact Type",
                    ),
                ),
                (
                    "contact_value",
                    models.CharField(
                        help_text="Email address or phone number",
                        max_length=100,
                        verbose_name="Contact Value",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this contact has been verified",
                        verbose_name="Verified",
                    ),
                ),
                (
                    "verified_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Notes"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_contacts",
                        to="members.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Contact",
                "verbose_name_plural": "Additional Contacts",
                "db_table": "member_additional_contacts",
                "ordering": ["contact_type"],
                "indexes": [
                    models.Index(
                        fields=["member", "contact_type"],
                        name="member_addi_member__ab2a8d_idx",
                    ),
                    models.Index(
                        fields=["is_verified"], name="member_addi_is_veri_65e148_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "contact_type", "contact_value"),
                        name="unique_member_contact",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="membergroup",
            index=models.Index(fields=["name"], name="member_grou_name_ad9ff4_idx"),
        ),
        migrations.AddIndex(
            model_name="membergroup",
            index=models.Index(
                fields=["group_type"], name="member_grou_group_t_f73a34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membergroup",
            index=models.Index(
                fields=["is_active"], name="member_grou_is_acti_a1157f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membergroup",
            index=models.Index(
                fields=["formation_date"], name="member_grou_formati_c5ad3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membergroup",
            index=models.Index(
                fields=["is_full"], name="member_grou_is_full_d86a7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["member", "group"], name="member_grou_member__7814da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(fields=["status"], name="member_grou_status_8fd2bd_idx"),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["is_active"], name="member_grou_is_acti_5e31b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["join_date"], name="member_grou_join_da_beb5da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(fields=["role"], name="member_grou_role_2aa39d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="groupmembership",
            unique_together={("member", "group")},
        ),
        migrations.AddIndex(
            model_name="memberpaymentmethod",
            index=models.Index(
                fields=["member", "is_primary"], name="member_paym_member__f43b26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberpaymentmethod",
            index=models.Index(
                fields=["member", "method_type"], name="member_paym_member__62674f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberpaymentmethod",
            index=models.Index(
                fields=["is_verified"], name="member_paym_is_veri_adc1de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberpaymentmethod",
            index=models.Index(
                fields=["is_active"], name="member_paym_is_acti_58cddf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberpaymentmethod",
            constraint=models.UniqueConstraint(
                fields=("member", "method_type", "account_number"),
                name="unique_member_payment_method",
            ),
        ),
        migrations.AddIndex(
            model_name="nextofkin",
            index=models.Index(
                fields=["member", "is_primary"], name="member_next_member__628a5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nextofkin",
            index=models.Index(
                fields=["member", "is_emergency_contact"],
                name="member_next_member__a9ca11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nextofkin",
            index=models.Index(
                fields=["member", "is_beneficiary"],
                name="member_next_member__981550_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nextofkin",
            index=models.Index(
                fields=["contact"], name="member_next_contact_e3e387_idx"
            ),
        ),
    ]
