# Generated by Django 5.2 on 2025-12-29 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Model Type"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Object ID"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        max_length=200, verbose_name="Object Representation"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Action",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary of field changes: {'field_name': {'old': 'value', 'new': 'value'}}",
                        verbose_name="Changes",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who performed this action",
                        max_length=50,
                        null=True,
                        verbose_name="User ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, max_length=255, verbose_name="User Email"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="User Name"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "change_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Change Reason"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Session Key"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Request Path"
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="utils_audit_content_131a61_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="utils_audit_user_id_9929fa_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="utils_audit_timesta_d9644a_idx"
                    ),
                    models.Index(
                        fields=["action"], name="utils_audit_action_1d6570_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialAuditLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DEPOSIT_RECEIVE", "Deposit Received"),
                            ("WITHDRAWAL_PROCESS", "Withdrawal Processed"),
                            ("TRANSFER_EXECUTE", "Transfer Executed"),
                            ("BALANCE_ADJUST", "Member Balance Adjusted"),
                            ("LOAN_APPLICATION", "Loan Application Submitted"),
                            ("LOAN_APPROVE", "Loan Approved"),
                            ("LOAN_REJECT", "Loan Rejected"),
                            ("LOAN_DISBURSE", "Loan Disbursed"),
                            ("LOAN_PAYMENT", "Loan Payment Received"),
                            ("LOAN_RESTRUCTURE", "Loan Restructured"),
                            ("LOAN_WRITEOFF", "Loan Written Off"),
                            ("SAVINGS_OPEN", "Savings Account Opened"),
                            ("SAVINGS_CLOSE", "Savings Account Closed"),
                            ("SAVINGS_DEPOSIT", "Savings Deposit"),
                            ("SAVINGS_WITHDRAWAL", "Savings Withdrawal"),
                            ("INTEREST_CREDIT", "Interest Credited"),
                            ("SHARE_PURCHASE", "Shares Purchased"),
                            ("SHARE_TRANSFER", "Shares Transferred"),
                            ("SHARE_WITHDRAWAL", "Shares Withdrawn"),
                            ("DIVIDEND_DECLARE", "Dividend Declared"),
                            ("DIVIDEND_DISTRIBUTE", "Dividend Distributed"),
                            ("DIVIDEND_CALCULATION", "Dividend Calculated"),
                            ("FEE_CHARGE", "Fee Charged"),
                            ("FEE_WAIVER", "Fee Waived"),
                            ("PENALTY_CHARGE", "Penalty Charged"),
                            ("FINANCIAL_REPORT_GENERATE", "Financial Report Generated"),
                            ("ACCOUNT_CREATE", "Account Created"),
                            ("ACCOUNT_UPDATE", "Account Updated"),
                            ("JOURNAL_POST", "Journal Entry Posted"),
                            ("RECONCILIATION", "Account Reconciliation"),
                            ("FINANCIAL_DATA_EXPORT", "Financial Data Exported"),
                            ("SETTINGS_CHANGE", "Financial Settings Changed"),
                            ("USER_ACCESS_FINANCIAL", "Financial Module Accessed"),
                            ("EXPENSE_CREATE", "Expense Created"),
                            ("EXPENSE_APPROVE", "Expense Approved"),
                            ("BUDGET_CREATE", "Budget Created"),
                            ("BUDGET_APPROVE", "Budget Approved"),
                            ("TAX_CALCULATE", "Tax Calculated"),
                            ("TAX_WITHHOLD", "Tax Withheld"),
                            ("TAX_REMIT", "Tax Remitted"),
                            ("TAX_REPORT", "Tax Report Generated"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who performed this action",
                        max_length=50,
                        null=True,
                        verbose_name="User ID",
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=200, null=True)),
                ("user_role", models.CharField(blank=True, max_length=100, null=True)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "object_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "amount_involved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monetary amount involved in the action",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(blank=True, default="UGX", max_length=3)),
                (
                    "member_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "member_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "member_account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("period_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "period_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, help_text="Values before change", null=True
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="Values after change", null=True
                    ),
                ),
                (
                    "changes_summary",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable summary of changes",
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "compliance_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Compliance-related flags or concerns",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context-specific data",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "is_automated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this action was performed automatically by the system",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        help_text="For grouping related bulk operations",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Audit Log",
                "verbose_name_plural": "Financial Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "action"],
                        name="utils_finan_timesta_2bc6fc_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="utils_finan_user_id_aa50a1_idx",
                    ),
                    models.Index(
                        fields=["member_id", "timestamp"],
                        name="utils_finan_member__7138cb_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "timestamp"],
                        name="utils_finan_risk_le_978129_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="utils_finan_ip_addr_99ad88_idx",
                    ),
                    models.Index(
                        fields=["period_id", "action"],
                        name="utils_finan_period__a75b25_idx",
                    ),
                ],
            },
        ),
    ]
