# Generated by Django 5.2 on 2025-12-29 07:38

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "sacco_currency",
                    djmoney.models.fields.CurrencyField(
                        default="UGX",
                        help_text="Primary currency for this SACCO",
                        max_length=3,
                    ),
                ),
                (
                    "currency_position",
                    models.CharField(
                        choices=[
                            ("BEFORE", "Before amount (UGX 100.00)"),
                            ("AFTER", "After amount (100.00 UGX)"),
                            ("BEFORE_NO_SPACE", "Before, no space (UGX100.00)"),
                            ("AFTER_NO_SPACE", "After, no space (100.00UGX)"),
                        ],
                        default="BEFORE",
                        max_length=20,
                        verbose_name="Currency Position",
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Number of decimal places for currency display",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Decimal Places",
                    ),
                ),
                (
                    "use_thousand_separator",
                    models.BooleanField(
                        default=True, verbose_name="Use Thousand Separator"
                    ),
                ),
                (
                    "default_loan_term_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Default loan repayment period in days",
                        verbose_name="Default Loan Term (Days)",
                    ),
                ),
                (
                    "default_interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("12.00"),
                        help_text="Default annual interest rate percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Default Interest Rate (%)",
                    ),
                ),
                (
                    "late_payment_penalty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Monthly penalty rate for late loan payments",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Late Payment Penalty Rate (%)",
                    ),
                ),
                (
                    "grace_period_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Grace period before late payment penalties apply",
                        verbose_name="Loan Grace Period (Days)",
                    ),
                ),
                (
                    "minimum_loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50000.00"),
                        help_text="Minimum amount for loan applications",
                        max_digits=12,
                        verbose_name="Minimum Loan Amount",
                    ),
                ),
                (
                    "maximum_loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000000.00"),
                        help_text="Maximum amount for loan applications",
                        max_digits=12,
                        verbose_name="Maximum Loan Amount",
                    ),
                ),
                (
                    "minimum_savings_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000.00"),
                        help_text="Minimum balance required in savings account",
                        max_digits=12,
                        verbose_name="Minimum Savings Balance",
                    ),
                ),
                (
                    "savings_interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Annual interest rate on savings",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Savings Interest Rate (%)",
                    ),
                ),
                (
                    "share_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5000.00"),
                        help_text="Value of one share in SACCO currency",
                        max_digits=12,
                        verbose_name="Share Value",
                    ),
                ),
                (
                    "minimum_shares",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum number of shares a member must own",
                        verbose_name="Minimum Shares Required",
                    ),
                ),
                (
                    "loan_approval_required",
                    models.BooleanField(
                        default=True,
                        help_text="Loans require approval before disbursement",
                        verbose_name="Loan Approval Required",
                    ),
                ),
                (
                    "withdrawal_approval_required",
                    models.BooleanField(
                        default=False,
                        help_text="Large withdrawals require approval",
                        verbose_name="Withdrawal Approval Required",
                    ),
                ),
                (
                    "withdrawal_approval_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500000.00"),
                        help_text="Withdrawals above this amount require approval",
                        max_digits=12,
                        verbose_name="Withdrawal Approval Limit",
                    ),
                ),
                (
                    "send_transaction_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Send notifications for transactions",
                        verbose_name="Send Transaction Notifications",
                    ),
                ),
                (
                    "send_loan_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Send reminders for upcoming loan payments",
                        verbose_name="Send Loan Payment Reminders",
                    ),
                ),
                (
                    "send_dividend_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Send notifications when dividends are distributed",
                        verbose_name="Send Dividend Notifications",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Settings",
                "verbose_name_plural": "Financial Settings",
            },
        ),
        migrations.CreateModel(
            name="SaccoConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "period_system",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly (12 per year)"),
                            ("quarterly", "Quarterly (4 per year)"),
                            ("biannual", "Biannual (2 per year)"),
                            ("annual", "Annual (1 per year)"),
                            ("custom", "Custom System"),
                        ],
                        default="monthly",
                        help_text="The operational period system used by the SACCO",
                        max_length=15,
                        verbose_name="Operational Period System",
                    ),
                ),
                (
                    "periods_per_year",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Number of operational periods in one fiscal year (1-52)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                        verbose_name="Periods Per Year",
                    ),
                ),
                (
                    "period_naming_convention",
                    models.CharField(
                        choices=[
                            ("numeric", "Numeric (Period 1, Period 2, etc.)"),
                            ("ordinal", "Ordinal (First Period, Second Period, etc.)"),
                            ("monthly", "Monthly (January, February, etc.)"),
                            ("quarterly", "Quarterly (Q1, Q2, Q3, Q4)"),
                            ("alpha", "Alphabetical (Period A, Period B, etc.)"),
                            ("roman", "Roman Numerals (Period I, Period II, etc.)"),
                            ("custom", "Custom Names"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Period Naming Convention",
                    ),
                ),
                (
                    "custom_period_names",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Custom names for each period position. E.g., {"1": "First Quarter", "2": "Second Quarter"}',
                        verbose_name="Custom Period Names",
                    ),
                ),
                (
                    "fiscal_year_type",
                    models.CharField(
                        choices=[
                            ("calendar", "Calendar Year (Jan-Dec)"),
                            ("financial_apr", "Financial Year April (Apr-Mar)"),
                            ("financial_jul", "Financial Year July (Jul-Jun)"),
                            ("financial_oct", "Financial Year October (Oct-Sep)"),
                            ("custom", "Custom Year Dates"),
                        ],
                        default="calendar",
                        help_text="When your fiscal year typically runs",
                        max_length=15,
                        verbose_name="Fiscal Year Type",
                    ),
                ),
                (
                    "fiscal_year_start_month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=1,
                        help_text="Month when fiscal year typically starts (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Fiscal Year Start Month",
                    ),
                ),
                (
                    "fiscal_year_start_day",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Day when fiscal year typically starts",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Fiscal Year Start Day",
                    ),
                ),
                (
                    "dividend_calculation_method",
                    models.CharField(
                        choices=[
                            ("SHARE_BASED", "Based on Share Capital"),
                            ("SAVINGS_BASED", "Based on Savings Balance"),
                            ("COMBINED", "Combined (Shares + Savings)"),
                        ],
                        default="SHARE_BASED",
                        help_text="Method used to calculate member dividends",
                        max_length=20,
                        verbose_name="Dividend Calculation Method",
                    ),
                ),
                (
                    "dividend_distribution_frequency",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual"),
                            ("BIANNUAL", "Bi-annual"),
                            ("QUARTERLY", "Quarterly"),
                        ],
                        default="ANNUAL",
                        help_text="How often dividends are distributed to members",
                        max_length=15,
                        verbose_name="Dividend Distribution Frequency",
                    ),
                ),
                (
                    "enable_automatic_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Send automatic payment and deadline reminders",
                        verbose_name="Enable Automatic Reminders",
                    ),
                ),
                (
                    "enable_sms",
                    models.BooleanField(
                        default=True,
                        help_text="Send SMS notifications to members",
                        verbose_name="Enable SMS Notifications",
                    ),
                ),
                (
                    "enable_email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Send email notifications",
                        verbose_name="Enable Email Notifications",
                    ),
                ),
            ],
            options={
                "verbose_name": "SACCO Configuration",
                "verbose_name_plural": "SACCO Configurations",
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., '2024', '2024/2025', 'FY 2024-2025'",
                        max_length=50,
                        unique=True,
                        verbose_name="Fiscal Year Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code e.g., 'FY2024', '2024-25'",
                        max_length=20,
                        unique=True,
                        verbose_name="Fiscal Year Code",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True,
                        help_text="When this fiscal year begins",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_index=True,
                        help_text="When this fiscal year ends",
                        verbose_name="End Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only one fiscal year can be active at a time",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Fiscal year has been closed and finalized",
                        verbose_name="Is Closed",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Fiscal year is locked for editing (for auditing)",
                        verbose_name="Is Locked",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this fiscal year",
                        verbose_name="Description",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this fiscal year was closed",
                        null=True,
                        verbose_name="Closed At",
                    ),
                ),
                (
                    "closed_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who closed this fiscal year",
                        max_length=50,
                        null=True,
                        verbose_name="Closed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Year",
                "verbose_name_plural": "Fiscal Years",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="core_fiscal_start_d_53aa6e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_fiscal_status_14550a_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="core_fiscal_is_acti_2bfcbd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'MTN Mobile Money', 'Cash', 'Bank Transfer - Stanbic'",
                        max_length=100,
                        verbose_name="Payment Method Name",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("CARD", "Card Payment"),
                            ("DIRECT_DEBIT", "Direct Debit"),
                            ("STANDING_ORDER", "Standing Order"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Method Type",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this payment method (e.g., 'MTN_MM', 'CASH', 'BNK_STANBIC')",
                        max_length=20,
                        unique=True,
                        verbose_name="Method Code",
                    ),
                ),
                (
                    "mobile_money_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MTN", "MTN Mobile Money"),
                            ("AIRTEL", "Airtel Money"),
                            ("AFRICELL", "Africell Money"),
                            ("OTHER", "Other Provider"),
                        ],
                        help_text="Only for mobile money payment methods",
                        max_length=20,
                        null=True,
                        verbose_name="Mobile Money Provider",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank name for bank transfer methods",
                        max_length=100,
                        verbose_name="Bank Name",
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True,
                        help_text="SACCO's bank account number for this method",
                        max_length=50,
                        verbose_name="Bank Account Number",
                    ),
                ),
                (
                    "bank_branch",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bank Branch"
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True,
                        help_text="For international transfers",
                        max_length=20,
                        verbose_name="SWIFT/BIC Code",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this payment method is currently available",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default payment method for transactions",
                        verbose_name="Is Default",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Transactions using this method require approval",
                        verbose_name="Requires Approval",
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum amount for transactions using this method",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Minimum Transaction Amount",
                    ),
                ),
                (
                    "maximum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum amount for transactions using this method",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Maximum Transaction Amount",
                    ),
                ),
                (
                    "daily_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total daily limit for this payment method",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Daily Transaction Limit",
                    ),
                ),
                (
                    "has_transaction_fee",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this payment method incurs transaction fees",
                        verbose_name="Has Transaction Fee",
                    ),
                ),
                (
                    "transaction_fee_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIXED", "Fixed Amount"),
                            ("PERCENTAGE", "Percentage of Amount"),
                            ("TIERED", "Tiered (Based on Amount)"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Transaction Fee Type",
                    ),
                ),
                (
                    "transaction_fee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed fee amount or percentage rate",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Transaction Fee Amount",
                    ),
                ),
                (
                    "fee_bearer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MEMBER", "Member Pays"),
                            ("SACCO", "SACCO Pays"),
                            ("SHARED", "Shared"),
                        ],
                        default="MEMBER",
                        max_length=20,
                        verbose_name="Fee Bearer",
                    ),
                ),
                (
                    "processing_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Instant', '1-2 business days', '3-5 working days'",
                        max_length=100,
                        verbose_name="Processing Time",
                    ),
                ),
                (
                    "requires_reference",
                    models.BooleanField(
                        default=False,
                        help_text="Transactions require a reference/transaction ID",
                        verbose_name="Requires Reference Number",
                    ),
                ),
                (
                    "api_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Payment method has API integration",
                        verbose_name="API Enabled",
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="API endpoint for this payment method",
                        verbose_name="API Endpoint",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="Encrypted API key for integration",
                        max_length=255,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="CSS class for payment method icon (e.g., 'fa-mobile', 'fa-money-bill')",
                        max_length=50,
                        verbose_name="Icon CSS Class",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for UI display (e.g., '#FFCB05' for MTN yellow)",
                        max_length=7,
                        verbose_name="Color Code",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which to display this payment method",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions for members on how to use this payment method",
                        verbose_name="Payment Instructions",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this payment method (not shown to members)",
                        verbose_name="Internal Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["method_type", "is_active"],
                        name="core_paymen_method__95d3e0_idx",
                    ),
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="core_paymen_is_acti_1617cd_idx",
                    ),
                    models.Index(fields=["code"], name="core_paymen_code_3029fb_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'WHT on Savings Interest', 'Corporate Tax Rate'",
                        max_length=100,
                        verbose_name="Tax Name",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("WHT_INTEREST", "Withholding Tax on Interest"),
                            ("WHT_DIVIDEND", "Withholding Tax on Dividend"),
                            ("CORPORATE", "Corporate Income Tax"),
                            ("VAT", "Value Added Tax"),
                            ("LOCAL_SERVICE", "Local Service Tax"),
                            ("STAMP_DUTY", "Stamp Duty"),
                            ("OTHER", "Other Tax"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tax Type",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax rate as percentage (e.g., 15.00 for 15%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Tax Rate (%)",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        db_index=True,
                        help_text="Date when this tax rate becomes effective",
                        verbose_name="Effective From",
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date when this tax rate expires (leave blank for indefinite)",
                        null=True,
                        verbose_name="Effective To",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this tax rate is currently in use",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "applies_to_members",
                    models.BooleanField(
                        default=True,
                        help_text="Tax applies to member transactions",
                        verbose_name="Applies to Members",
                    ),
                ),
                (
                    "applies_to_sacco",
                    models.BooleanField(
                        default=False,
                        help_text="Tax applies to SACCO operations",
                        verbose_name="Applies to SACCO",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about this tax rate",
                        verbose_name="Description",
                    ),
                ),
                (
                    "legal_reference",
                    models.CharField(
                        blank=True,
                        help_text="Legal or regulatory reference for this tax",
                        max_length=255,
                        verbose_name="Legal Reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Rate",
                "verbose_name_plural": "Tax Rates",
                "ordering": ["-effective_from", "tax_type"],
                "indexes": [
                    models.Index(
                        fields=["tax_type", "effective_from"],
                        name="core_taxrat_tax_typ_37cb92_idx",
                    ),
                    models.Index(
                        fields=["is_active", "effective_from"],
                        name="core_taxrat_is_acti_c1a802_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'January', 'Q1', 'Month 1'",
                        max_length=100,
                        verbose_name="Period Name",
                    ),
                ),
                (
                    "period_number",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Sequential number within the fiscal year (1, 2, 3, etc.)",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Period Number",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True,
                        help_text="When this period begins",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_index=True,
                        help_text="When this period ends",
                        verbose_name="End Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only one period can be active at a time across all fiscal years",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Period has been closed and finalized",
                        verbose_name="Is Closed",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Period is locked for editing (for auditing)",
                        verbose_name="Is Locked",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this period",
                        verbose_name="Description",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this period was closed",
                        null=True,
                        verbose_name="Closed At",
                    ),
                ),
                (
                    "closed_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who closed this period",
                        max_length=50,
                        null=True,
                        verbose_name="Closed By",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        help_text="The fiscal year this period belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="core.fiscalyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "ordering": ["-fiscal_year__start_date", "period_number"],
                "indexes": [
                    models.Index(
                        fields=["fiscal_year", "period_number"],
                        name="core_fiscal_fiscal__5cc46d_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="core_fiscal_start_d_9a8d82_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_fiscal_status_8d866d_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="core_fiscal_is_acti_c5a532_idx"
                    ),
                ],
                "unique_together": {("fiscal_year", "period_number")},
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "abbreviation",
                    models.CharField(max_length=10, verbose_name="Abbreviation"),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Symbol"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "uom_type",
                    models.CharField(
                        choices=[
                            ("LENGTH", "Length"),
                            ("WEIGHT", "Weight"),
                            ("VOLUME", "Volume"),
                            ("AREA", "Area"),
                            ("QUANTITY", "Quantity"),
                            ("TIME", "Time"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="UOM Type",
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        help_text="Multiply by this factor to convert to the base unit",
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                        verbose_name="Conversion Factor",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "base_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="The base unit this unit is derived from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_units",
                        to="core.unitofmeasure",
                        verbose_name="Base Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["uom_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["uom_type", "is_active"],
                        name="core_unitof_uom_typ_91fe63_idx",
                    ),
                    models.Index(
                        fields=["base_unit", "uom_type"],
                        name="core_unitof_base_un_c43c97_idx",
                    ),
                    models.Index(
                        fields=["is_active", "uom_type"],
                        name="core_unitof_is_acti_ee09d7_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("conversion_factor__gt", 0)),
                        name="positive_conversion_factor",
                    )
                ],
            },
        ),
    ]
