# Generated by Django 5.2 on 2025-12-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialsettings",
            name="sacco_currency",
            field=models.CharField(
                default="UGX",
                help_text="Primary currency for this SACCO (ISO 4217 code)",
                max_length=3,
                verbose_name="SACCO Primary Currency",
            ),
        ),
    ]
