# Generated by Django 5.2 on 2025-12-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_financialsettings_sacco_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="saccoconfiguration",
            name="operational_timezone",
            field=models.CharField(
                default="Africa/Kampala",
                help_text="Timezone for fiscal periods, deadlines, and automated processes",
                max_length=63,
                verbose_name="Operational Timezone",
            ),
        ),
    ]
