# Generated by Django 5.2 on 2025-12-29 07:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the savings product",
                        max_length=100,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this savings product",
                        max_length=20,
                        unique=True,
                        verbose_name="Product Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the savings product",
                        verbose_name="Description",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Annual interest rate in percentage",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Interest Rate (%)",
                    ),
                ),
                (
                    "interest_calculation_method",
                    models.CharField(
                        choices=[
                            ("SIMPLE", "Simple Interest"),
                            ("COMPOUND", "Compound Interest"),
                            ("AVERAGE_BALANCE", "Average Balance"),
                            ("MINIMUM_BALANCE", "Minimum Balance"),
                            ("TIERED", "Tiered Interest"),
                            ("DAILY_BALANCE", "Daily Balance"),
                        ],
                        default="SIMPLE",
                        max_length=20,
                        verbose_name="Interest Calculation Method",
                    ),
                ),
                (
                    "interest_calculation_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="MONTHLY",
                        max_length=15,
                        verbose_name="Interest Calculation Frequency",
                    ),
                ),
                (
                    "interest_posting_frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("SEMI_ANNUALLY", "Semi-Annually"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="MONTHLY",
                        max_length=15,
                        verbose_name="Interest Posting Frequency",
                    ),
                ),
                (
                    "minimum_opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum amount required to open account",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Minimum Opening Balance",
                    ),
                ),
                (
                    "minimum_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum balance to maintain",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Minimum Balance",
                    ),
                ),
                (
                    "maximum_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum balance allowed (blank for no limit)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Maximum Balance",
                    ),
                ),
                (
                    "minimum_deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Minimum Deposit Amount",
                    ),
                ),
                (
                    "minimum_withdrawal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Minimum Withdrawal Amount",
                    ),
                ),
                (
                    "maximum_withdrawal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum withdrawal amount (blank for no limit)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Maximum Withdrawal Amount",
                    ),
                ),
                (
                    "allow_overdraft",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this product allows overdrafts",
                        verbose_name="Allow Overdraft",
                    ),
                ),
                (
                    "overdraft_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum overdraft amount allowed",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Overdraft Limit",
                    ),
                ),
                (
                    "overdraft_interest_rate",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Overdraft Interest Rate (%)",
                    ),
                ),
                (
                    "withdrawal_fee_flat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Withdrawal Fee (Flat)",
                    ),
                ),
                (
                    "withdrawal_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Withdrawal Fee (%)",
                    ),
                ),
                (
                    "deposit_fee_flat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Deposit Fee (Flat)",
                    ),
                ),
                (
                    "deposit_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Deposit Fee (%)",
                    ),
                ),
                (
                    "dormancy_period_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Days of inactivity before account becomes dormant",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Dormancy Period (Days)",
                    ),
                ),
                (
                    "account_maintenance_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Account Maintenance Fee",
                    ),
                ),
                (
                    "maintenance_fee_frequency",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="NONE",
                        max_length=15,
                        verbose_name="Maintenance Fee Frequency",
                    ),
                ),
                (
                    "is_fixed_deposit",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a fixed deposit product",
                        verbose_name="Is Fixed Deposit",
                    ),
                ),
                (
                    "minimum_term_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum term in days for fixed deposits",
                        verbose_name="Minimum Term (Days)",
                    ),
                ),
                (
                    "maximum_term_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum term in days (blank for no limit)",
                        null=True,
                        verbose_name="Maximum Term (Days)",
                    ),
                ),
                (
                    "early_withdrawal_penalty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Penalty as percentage of withdrawn amount",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Early Withdrawal Penalty (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this product is available for new accounts",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_group_product",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a group savings product",
                        verbose_name="Is Group Product",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Whether new accounts require approval",
                        verbose_name="Requires Approval",
                    ),
                ),
                (
                    "is_main_account",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary/main savings product",
                        verbose_name="Is Main Account Product",
                    ),
                ),
                (
                    "gl_account_code",
                    models.CharField(
                        blank=True,
                        help_text="General Ledger account code",
                        max_length=20,
                        null=True,
                        verbose_name="GL Account Code",
                    ),
                ),
                (
                    "maximum_accounts_per_member",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of accounts of this type per member",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maximum Accounts Per Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savings Product",
                "verbose_name_plural": "Savings Products",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "name"],
                        name="savings_sav_is_acti_2c5a3b_idx",
                    ),
                    models.Index(fields=["code"], name="savings_sav_code_f97835_idx"),
                    models.Index(
                        fields=["is_main_account"],
                        name="savings_sav_is_main_1175eb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavingsAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Unique account number",
                        max_length=30,
                        unique=True,
                        verbose_name="Account Number",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Current Balance",
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Balance available for withdrawal (current - holds)",
                        max_digits=15,
                        verbose_name="Available Balance",
                    ),
                ),
                (
                    "hold_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount on hold (not available for withdrawal)",
                        max_digits=15,
                        verbose_name="Hold Amount",
                    ),
                ),
                (
                    "overdraft_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current overdraft balance",
                        max_digits=15,
                        verbose_name="Overdraft Amount",
                    ),
                ),
                (
                    "accrued_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Interest earned but not yet posted",
                        max_digits=12,
                        verbose_name="Accrued Interest",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DORMANT", "Dormant"),
                            ("FROZEN", "Frozen"),
                            ("CLOSED", "Closed"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="PENDING_APPROVAL",
                        max_length=20,
                        verbose_name="Account Status",
                    ),
                ),
                (
                    "opening_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when account was opened",
                        verbose_name="Opening Date",
                    ),
                ),
                (
                    "activated_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when account was activated",
                        null=True,
                        verbose_name="Activated Date",
                    ),
                ),
                (
                    "closure_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when account was closed",
                        null=True,
                        verbose_name="Closure Date",
                    ),
                ),
                (
                    "maturity_date",
                    models.DateField(
                        blank=True,
                        help_text="For fixed deposits - when deposit matures",
                        null=True,
                        verbose_name="Maturity Date",
                    ),
                ),
                (
                    "last_interest_calculated_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Interest Calculated"
                    ),
                ),
                (
                    "last_interest_posted_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Interest Posted"
                    ),
                ),
                (
                    "total_interest_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total interest earned since opening",
                        max_digits=12,
                        verbose_name="Total Interest Earned",
                    ),
                ),
                (
                    "is_fixed_deposit",
                    models.BooleanField(default=False, verbose_name="Is Fixed Deposit"),
                ),
                (
                    "term_length_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Term length for fixed deposits",
                        null=True,
                        verbose_name="Term Length (Days)",
                    ),
                ),
                (
                    "fixed_deposit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Initial fixed deposit amount",
                        max_digits=15,
                        null=True,
                        verbose_name="Fixed Deposit Amount",
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to automatically renew fixed deposit",
                        verbose_name="Auto Renew",
                    ),
                ),
                (
                    "overdraft_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Overdraft Limit",
                    ),
                ),
                (
                    "overdraft_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Overdraft Expiry Date"
                    ),
                ),
                (
                    "account_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Account UUID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Group this account belongs to (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_savings_accounts",
                        to="members.membergroup",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member who owns this account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_accounts",
                        to="members.member",
                    ),
                ),
                (
                    "savings_product",
                    models.ForeignKey(
                        help_text="Savings product type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="savings.savingsproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savings Account",
                "verbose_name_plural": "Savings Accounts",
                "ordering": ["-opening_date", "account_number"],
            },
        ),
        migrations.CreateModel(
            name="InterestTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        help_text="Name of this interest tier",
                        max_length=50,
                        verbose_name="Tier Name",
                    ),
                ),
                (
                    "min_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Minimum Balance",
                    ),
                ),
                (
                    "max_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum balance for this tier (blank for no upper limit)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Maximum Balance",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Interest Rate (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "savings_product",
                    models.ForeignKey(
                        help_text="Savings product this tier belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_tiers",
                        to="savings.savingsproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interest Tier",
                "verbose_name_plural": "Interest Tiers",
                "ordering": ["savings_product", "min_balance"],
            },
        ),
        migrations.CreateModel(
            name="SavingsTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Unique transaction identifier",
                        max_length=30,
                        unique=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("TRANSFER_IN", "Transfer In"),
                            ("TRANSFER_OUT", "Transfer Out"),
                            ("INTEREST", "Interest"),
                            ("FEE", "Fee"),
                            ("TAX", "Tax"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("REVERSAL", "Reversal"),
                            ("DIVIDEND", "Dividend"),
                            ("MAINTENANCE_FEE", "Maintenance Fee"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Transaction Amount",
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Fees",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Transaction Date",
                    ),
                ),
                (
                    "post_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date transaction is posted to account",
                        verbose_name="Post Date",
                    ),
                ),
                (
                    "value_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date from which interest is calculated",
                        verbose_name="Value Date",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference number (e.g., mobile money ref)",
                        max_length=100,
                        null=True,
                        verbose_name="Reference Number",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Account balance after this transaction",
                        max_digits=15,
                        verbose_name="Running Balance",
                    ),
                ),
                (
                    "is_reversed",
                    models.BooleanField(default=False, verbose_name="Is Reversed"),
                ),
                (
                    "reversal_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Reversal Reason"
                    ),
                ),
                (
                    "reversal_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reversal Date"
                    ),
                ),
                (
                    "reversed_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who reversed the transaction",
                        max_length=50,
                        null=True,
                        verbose_name="Reversed By",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Savings account this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="savings.savingsaccount",
                    ),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="savings_transactions",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "linked_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destination account for transfers",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_transactions",
                        to="savings.savingsaccount",
                    ),
                ),
                (
                    "linked_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked transaction for transfers",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_to",
                        to="savings.savingstransaction",
                    ),
                ),
                (
                    "original_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original transaction being reversed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversal_transactions",
                        to="savings.savingstransaction",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="savings_transactions",
                        to="core.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savings Transaction",
                "verbose_name_plural": "Savings Transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="InterestCalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "calculation_date",
                    models.DateField(
                        help_text="Date when interest was calculated",
                        verbose_name="Calculation Date",
                    ),
                ),
                (
                    "period_start_date",
                    models.DateField(verbose_name="Period Start Date"),
                ),
                ("period_end_date", models.DateField(verbose_name="Period End Date")),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("SIMPLE", "Simple Interest"),
                            ("COMPOUND", "Compound Interest"),
                            ("AVERAGE_BALANCE", "Average Balance"),
                            ("MINIMUM_BALANCE", "Minimum Balance"),
                            ("TIERED", "Tiered Interest"),
                            ("DAILY_BALANCE", "Daily Balance"),
                        ],
                        max_length=20,
                        verbose_name="Calculation Method",
                    ),
                ),
                (
                    "average_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Average Balance",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Opening Balance",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Closing Balance",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=5, max_digits=8, verbose_name="Interest Rate (%)"
                    ),
                ),
                (
                    "days_calculated",
                    models.PositiveIntegerField(verbose_name="Days Calculated"),
                ),
                (
                    "gross_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Gross Interest",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Tax Rate (%)",
                    ),
                ),
                (
                    "withholding_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Withholding Tax",
                    ),
                ),
                (
                    "net_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Net Interest",
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(default=False, verbose_name="Is Posted"),
                ),
                (
                    "posted_date",
                    models.DateField(blank=True, null=True, verbose_name="Posted Date"),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interest_calculations",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this calculation is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_calculations",
                        to="savings.savingsaccount",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interest_calculation",
                        to="savings.savingstransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interest Calculation",
                "verbose_name_plural": "Interest Calculations",
                "ordering": ["-calculation_date"],
            },
        ),
        migrations.CreateModel(
            name="StandingOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Transfer Amount",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BIWEEKLY", "Bi-Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        max_length=15,
                        verbose_name="Frequency",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for indefinite standing order",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                ("next_run_date", models.DateField(verbose_name="Next Run Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                        ],
                        db_index=True,
                        default="PENDING_APPROVAL",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "execution_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Execution Count"
                    ),
                ),
                (
                    "last_execution_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Execution Date"
                    ),
                ),
                (
                    "last_execution_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Last Execution Status",
                    ),
                ),
                (
                    "last_failure_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Last Failure Reason"
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account to transfer to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standing_orders_in",
                        to="savings.savingsaccount",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        help_text="Account to transfer from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_orders_out",
                        to="savings.savingsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standing Order",
                "verbose_name_plural": "Standing Orders",
                "ordering": ["next_run_date"],
            },
        ),
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Goal Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("EDUCATION", "Education"),
                            ("HOUSING", "Housing/Property"),
                            ("BUSINESS", "Business"),
                            ("EMERGENCY", "Emergency Fund"),
                            ("RETIREMENT", "Retirement"),
                            ("TRAVEL", "Travel"),
                            ("WEDDING", "Wedding"),
                            ("VEHICLE", "Vehicle Purchase"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Goal Type",
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Target Amount",
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Current Amount",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Start Date"
                    ),
                ),
                ("target_date", models.DateField(verbose_name="Target Date")),
                (
                    "is_achieved",
                    models.BooleanField(default=False, verbose_name="Is Achieved"),
                ),
                (
                    "achievement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Achievement Date"
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Progress Percentage",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Savings account linked to this goal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_goals",
                        to="savings.savingsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savings Goal",
                "verbose_name_plural": "Savings Goals",
                "ordering": ["target_date"],
                "indexes": [
                    models.Index(
                        fields=["account", "is_achieved"],
                        name="savings_sav_account_6ab32b_idx",
                    ),
                    models.Index(
                        fields=["target_date"], name="savings_sav_target__58ae76_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="savingsaccount",
            index=models.Index(
                fields=["account_number"], name="savings_sav_account_5fdcd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savingsaccount",
            index=models.Index(
                fields=["member", "status"], name="savings_sav_member__4b629a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savingsaccount",
            index=models.Index(
                fields=["savings_product", "is_fixed_deposit"],
                name="savings_sav_savings_26e8a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savingsaccount",
            index=models.Index(
                fields=["status", "opening_date"], name="savings_sav_status_98d0e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interesttier",
            index=models.Index(
                fields=["savings_product", "is_active"],
                name="savings_int_savings_7b5df6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interesttier",
            index=models.Index(
                fields=["min_balance"], name="savings_int_min_bal_eb411b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savingstransaction",
            index=models.Index(
                fields=["transaction_id"], name="savings_sav_transac_1b9c4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savingstransaction",
            index=models.Index(
                fields=["account", "transaction_date"],
                name="savings_sav_account_d3dda0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savingstransaction",
            index=models.Index(
                fields=["transaction_type", "post_date"],
                name="savings_sav_transac_d52162_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savingstransaction",
            index=models.Index(
                fields=["is_reversed"], name="savings_sav_is_reve_ba50b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savingstransaction",
            index=models.Index(
                fields=["financial_period"], name="savings_sav_financi_83a5db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interestcalculation",
            index=models.Index(
                fields=["account", "calculation_date"],
                name="savings_int_account_7eca1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interestcalculation",
            index=models.Index(
                fields=["is_posted", "posted_date"],
                name="savings_int_is_post_5dfba4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interestcalculation",
            index=models.Index(
                fields=["financial_period"], name="savings_int_financi_ccf4ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standingorder",
            index=models.Index(
                fields=["status", "next_run_date"], name="savings_sta_status_cbef1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standingorder",
            index=models.Index(
                fields=["source_account", "status"],
                name="savings_sta_source__813a28_idx",
            ),
        ),
    ]
