# Generated by Django 5.2 on 2025-12-29 07:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the loan product",
                        max_length=100,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this loan product",
                        max_length=20,
                        unique=True,
                        verbose_name="Product Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the loan product",
                        verbose_name="Description",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum loan amount that can be requested",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Minimum Loan Amount",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum loan amount that can be requested",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Maximum Loan Amount",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate in percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Interest Rate (%)",
                    ),
                ),
                (
                    "interest_type",
                    models.CharField(
                        choices=[
                            ("FLAT", "Flat Rate"),
                            ("REDUCING_BALANCE", "Reducing Balance"),
                            ("COMPOUND", "Compound Interest"),
                        ],
                        default="REDUCING_BALANCE",
                        max_length=20,
                        verbose_name="Interest Type",
                    ),
                ),
                (
                    "interest_calculation",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="Interest Calculation Frequency",
                    ),
                ),
                (
                    "loan_processing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Processing fee as percentage of loan amount",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Processing Fee (%)",
                    ),
                ),
                (
                    "insurance_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Insurance fee as percentage of loan amount",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Insurance Fee (%)",
                    ),
                ),
                (
                    "min_term",
                    models.PositiveIntegerField(
                        help_text="Minimum loan term in months",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Minimum Term (Months)",
                    ),
                ),
                (
                    "max_term",
                    models.PositiveIntegerField(
                        help_text="Maximum loan term in months",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maximum Term (Months)",
                    ),
                ),
                (
                    "repayment_cycle",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BI_WEEKLY", "Bi-Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="Repayment Cycle",
                    ),
                ),
                (
                    "grace_period",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Grace period in days before first payment is due",
                        verbose_name="Grace Period (Days)",
                    ),
                ),
                (
                    "minimum_savings_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum savings required as percentage of loan amount",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Minimum Savings Required (%)",
                    ),
                ),
                (
                    "minimum_shares_required",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum number of shares member must own",
                        verbose_name="Minimum Shares Required",
                    ),
                ),
                (
                    "guarantor_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether guarantors are required for this product",
                        verbose_name="Guarantor Required",
                    ),
                ),
                (
                    "number_of_guarantors",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of guarantors required",
                        verbose_name="Number of Guarantors",
                    ),
                ),
                (
                    "collateral_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether collateral is required",
                        verbose_name="Collateral Required",
                    ),
                ),
                (
                    "allow_top_up",
                    models.BooleanField(
                        default=False,
                        help_text="Allow members to top up existing loans",
                        verbose_name="Allow Top Up",
                    ),
                ),
                (
                    "allow_early_repayment",
                    models.BooleanField(
                        default=True,
                        help_text="Allow early/advance loan repayment",
                        verbose_name="Allow Early Repayment",
                    ),
                ),
                (
                    "early_repayment_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Early repayment penalty as percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Early Repayment Fee (%)",
                    ),
                ),
                (
                    "penalty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Late payment penalty percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Penalty Rate (%)",
                    ),
                ),
                (
                    "penalty_grace_period",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Days before penalty applies after due date",
                        verbose_name="Penalty Grace Period (Days)",
                    ),
                ),
                (
                    "penalty_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="MONTHLY",
                        help_text="How often penalty is calculated and applied",
                        max_length=20,
                        verbose_name="Penalty Frequency",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this product is available for new loans",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "gl_account_code",
                    models.CharField(
                        blank=True,
                        help_text="General Ledger account code for this product",
                        max_length=20,
                        null=True,
                        verbose_name="GL Account Code",
                    ),
                ),
                (
                    "maximum_loans_per_member",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum active loans a member can have of this type",
                        verbose_name="Maximum Loans Per Member",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Whether loan applications require approval",
                        verbose_name="Requires Approval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Product",
                "verbose_name_plural": "Loan Products",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "name"],
                        name="loans_loanp_is_acti_29b1b3_idx",
                    ),
                    models.Index(fields=["code"], name="loans_loanp_code_d8856e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        editable=False,
                        help_text="Unique application number",
                        max_length=20,
                        unique=True,
                        verbose_name="Application Number",
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Loan amount being requested",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Amount Requested",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        help_text="Purpose for which loan is being requested",
                        verbose_name="Loan Purpose",
                    ),
                ),
                (
                    "term_months",
                    models.PositiveIntegerField(
                        help_text="Requested loan term in months",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Loan Term (Months)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("DISBURSED", "Disbursed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=15,
                        verbose_name="Application Status",
                    ),
                ),
                (
                    "application_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date when application was created",
                        verbose_name="Application Date",
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when application was submitted for review",
                        null=True,
                        verbose_name="Submission Date",
                    ),
                ),
                (
                    "processing_fee_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether processing fee has been paid",
                        verbose_name="Processing Fee Paid",
                    ),
                ),
                (
                    "processing_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Processing Fee Amount",
                    ),
                ),
                (
                    "insurance_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Insurance Fee Amount",
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final approved loan amount (may differ from requested)",
                        max_digits=12,
                        null=True,
                        verbose_name="Approved Amount",
                    ),
                ),
                (
                    "approved_term",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Final approved loan term",
                        null=True,
                        verbose_name="Approved Term (Months)",
                    ),
                ),
                (
                    "approved_interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final approved interest rate",
                        max_digits=5,
                        null=True,
                        verbose_name="Approved Interest Rate (%)",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Rejection Reason"
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed Date"
                    ),
                ),
                (
                    "reviewed_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who reviewed the application",
                        max_length=50,
                        null=True,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
                (
                    "approved_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who approved the application",
                        max_length=50,
                        null=True,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "disbursement_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CASH", "Cash"),
                            ("SAVINGS_ACCOUNT", "Savings Account"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Disbursement Method",
                    ),
                ),
                (
                    "disbursement_account",
                    models.CharField(
                        blank=True,
                        help_text="Account number or phone number for disbursement",
                        max_length=100,
                        null=True,
                        verbose_name="Disbursement Account",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the application",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Financial period when application was submitted",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_applications",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member applying for the loan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_applications",
                        to="members.member",
                    ),
                ),
                (
                    "loan_product",
                    models.ForeignKey(
                        help_text="Loan product being applied for",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loans.loanproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Application",
                "verbose_name_plural": "Loan Applications",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "loan_number",
                    models.CharField(
                        help_text="Unique loan number",
                        max_length=20,
                        unique=True,
                        verbose_name="Loan Number",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original loan amount disbursed",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Principal Amount",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Interest Rate (%)",
                    ),
                ),
                (
                    "term_months",
                    models.PositiveIntegerField(
                        help_text="Loan term in months",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Loan Term (Months)",
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BI_WEEKLY", "Bi-Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        help_text="How often payments are due",
                        max_length=20,
                        verbose_name="Payment Frequency",
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateField(
                        help_text="Date when loan was disbursed",
                        verbose_name="Disbursement Date",
                    ),
                ),
                (
                    "first_payment_date",
                    models.DateField(
                        help_text="Date when first payment is due",
                        verbose_name="First Payment Date",
                    ),
                ),
                (
                    "expected_end_date",
                    models.DateField(
                        help_text="Expected final payment date",
                        verbose_name="Expected End Date",
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual date when loan was fully paid",
                        null=True,
                        verbose_name="Actual End Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAID", "Paid"),
                            ("DEFAULTED", "Defaulted"),
                            ("WRITTEN_OFF", "Written Off"),
                            ("RESTRUCTURED", "Restructured"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="Loan Status",
                    ),
                ),
                (
                    "total_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total interest to be paid over loan term",
                        max_digits=12,
                        verbose_name="Total Interest",
                    ),
                ),
                (
                    "total_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total fees charged (processing, insurance, etc.)",
                        max_digits=10,
                        verbose_name="Total Fees",
                    ),
                ),
                (
                    "total_payable",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount to be repaid (principal + interest + fees)",
                        max_digits=12,
                        verbose_name="Total Payable",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount paid so far",
                        max_digits=12,
                        verbose_name="Total Paid",
                    ),
                ),
                (
                    "total_paid_principal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Paid Principal",
                    ),
                ),
                (
                    "total_paid_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Paid Interest",
                    ),
                ),
                (
                    "total_paid_penalties",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Total Paid Penalties",
                    ),
                ),
                (
                    "total_paid_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Total Paid Fees",
                    ),
                ),
                (
                    "outstanding_principal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Outstanding Principal",
                    ),
                ),
                (
                    "outstanding_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Outstanding Interest",
                    ),
                ),
                (
                    "outstanding_penalties",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Outstanding Penalties",
                    ),
                ),
                (
                    "outstanding_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Outstanding Fees",
                    ),
                ),
                (
                    "outstanding_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Outstanding Total",
                    ),
                ),
                (
                    "days_in_arrears",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of days payment is overdue",
                        verbose_name="Days in Arrears",
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Payment Date"
                    ),
                ),
                (
                    "next_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Payment Date"
                    ),
                ),
                (
                    "next_payment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Next Payment Amount",
                    ),
                ),
                (
                    "disbursement_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Disbursement Reference",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "disbursement_method",
                    models.ForeignKey(
                        blank=True,
                        help_text="Method used for loan disbursement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disbursed_loans",
                        to="core.paymentmethod",
                    ),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Financial period when loan was disbursed",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member who received the loan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="members.member",
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        blank=True,
                        help_text="Original loan application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_loan",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "loan_product",
                    models.ForeignKey(
                        help_text="Loan product type",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loans.loanproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "ordering": ["-disbursement_date"],
            },
        ),
        migrations.CreateModel(
            name="LoanSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveIntegerField(
                        help_text="Sequential installment number",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Installment Number",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Date when payment is due", verbose_name="Due Date"
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Principal Amount",
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Interest Amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Paid Amount",
                    ),
                ),
                (
                    "paid_principal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Paid Principal",
                    ),
                ),
                (
                    "paid_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Paid Interest",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Balance",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("WAIVED", "Waived"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(blank=True, null=True, verbose_name="Paid Date"),
                ),
                (
                    "days_late",
                    models.IntegerField(
                        default=0,
                        help_text="Number of days overdue",
                        verbose_name="Days Late",
                    ),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Financial period this installment falls in",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_schedules",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        help_text="Loan this installment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Schedule",
                "verbose_name_plural": "Loan Schedules",
                "ordering": ["loan", "installment_number"],
            },
        ),
        migrations.CreateModel(
            name="LoanCollateral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "collateral_type",
                    models.CharField(
                        choices=[
                            ("REAL_ESTATE", "Real Estate"),
                            ("VEHICLE", "Vehicle"),
                            ("EQUIPMENT", "Equipment/Machinery"),
                            ("FIXED_DEPOSIT", "Fixed Deposit"),
                            ("SHARES", "Company Shares"),
                            ("INVENTORY", "Business Inventory"),
                            ("RECEIVABLES", "Accounts Receivable"),
                            ("OTHER", "Other Assets"),
                        ],
                        max_length=15,
                        verbose_name="Collateral Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the collateral",
                        verbose_name="Description",
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated market value",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Estimated Value",
                    ),
                ),
                (
                    "appraised_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Professional appraisal value",
                        max_digits=12,
                        null=True,
                        verbose_name="Appraised Value",
                    ),
                ),
                (
                    "forced_sale_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated value in forced sale scenario",
                        max_digits=12,
                        null=True,
                        verbose_name="Forced Sale Value",
                    ),
                ),
                (
                    "valuation_date",
                    models.DateField(
                        help_text="Date when valuation was done",
                        verbose_name="Valuation Date",
                    ),
                ),
                (
                    "location",
                    models.TextField(
                        blank=True,
                        help_text="Physical location of the collateral",
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        help_text="Legal owner of the collateral",
                        max_length=200,
                        verbose_name="Owner Name",
                    ),
                ),
                (
                    "ownership_document_number",
                    models.CharField(
                        blank=True,
                        help_text="Title deed, registration number, etc.",
                        max_length=100,
                        null=True,
                        verbose_name="Ownership Document Number",
                    ),
                ),
                (
                    "ownership_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="collateral_documents/",
                        verbose_name="Ownership Document",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="collateral_photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "appraisal_report",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="collateral_appraisals/",
                        verbose_name="Appraisal Report",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                (
                    "verified_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who verified the collateral",
                        max_length=50,
                        null=True,
                        verbose_name="Verified By",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Verification Notes"
                    ),
                ),
                (
                    "is_insured",
                    models.BooleanField(default=False, verbose_name="Is Insured"),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Insurance Policy Number",
                    ),
                ),
                (
                    "insurance_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Insurance Expiry Date"
                    ),
                ),
                (
                    "loan_application",
                    models.ForeignKey(
                        help_text="Loan application this collateral is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaterals",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Collateral",
                "verbose_name_plural": "Loan Collaterals",
                "ordering": ["-valuation_date"],
                "indexes": [
                    models.Index(
                        fields=["loan_application", "is_verified"],
                        name="loans_loanc_loan_ap_79cda4_idx",
                    ),
                    models.Index(
                        fields=["collateral_type"],
                        name="loans_loanc_collate_34896b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION_FORM", "Application Form"),
                            ("ID_DOCUMENT", "ID Document"),
                            ("PAYSLIP", "Payslip"),
                            ("BANK_STATEMENT", "Bank Statement"),
                            ("BUSINESS_REGISTRATION", "Business Registration"),
                            ("TAX_RETURNS", "Tax Returns"),
                            ("COLLATERAL_DOC", "Collateral Document"),
                            ("APPRAISAL_REPORT", "Appraisal Report"),
                            ("CONTRACT", "Loan Contract"),
                            ("PROMISSORY_NOTE", "Promissory Note"),
                            ("GUARANTOR_FORM", "Guarantor Form"),
                            ("OTHER", "Other Document"),
                        ],
                        max_length=25,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="loan_documents/", verbose_name="Document File"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Document Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this document is mandatory",
                        verbose_name="Is Required",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                (
                    "verified_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who verified the document",
                        max_length=50,
                        null=True,
                        verbose_name="Verified By",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Verification Notes"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Document expiry date (if applicable)",
                        null=True,
                        verbose_name="Expiry Date",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Application this document belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Loan this document belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Document",
                "verbose_name_plural": "Loan Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document_type"], name="loans_loand_documen_968980_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="loans_loand_is_veri_52b37e_idx"
                    ),
                    models.Index(
                        fields=["is_required", "is_verified"],
                        name="loans_loand_is_requ_658cbf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanGuarantor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "guarantee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount being guaranteed",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Guarantee Amount",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="Relationship between guarantor and applicant",
                        max_length=100,
                        null=True,
                        verbose_name="Relationship to Applicant",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                        verbose_name="Guarantor Status",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Request Date"
                    ),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Response Date"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "guarantor",
                    models.ForeignKey(
                        help_text="Member acting as guarantor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantor_for",
                        to="members.member",
                    ),
                ),
                (
                    "loan_application",
                    models.ForeignKey(
                        help_text="Loan application being guaranteed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantors",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Guarantor",
                "verbose_name_plural": "Loan Guarantors",
                "ordering": ["-request_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "request_date"],
                        name="loans_loang_status_ea8f6a_idx",
                    ),
                    models.Index(
                        fields=["guarantor", "status"],
                        name="loans_loang_guarant_cc7152_idx",
                    ),
                ],
                "unique_together": {("loan_application", "guarantor")},
            },
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        help_text="Unique payment identifier",
                        max_length=20,
                        unique=True,
                        verbose_name="Payment Number",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        help_text="Date when payment was made",
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount paid",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Total Payment Amount",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount applied to principal",
                        max_digits=12,
                        verbose_name="Principal Amount",
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount applied to interest",
                        max_digits=12,
                        verbose_name="Interest Amount",
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount applied to penalties",
                        max_digits=10,
                        verbose_name="Penalty Amount",
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount applied to fees",
                        max_digits=10,
                        verbose_name="Fee Amount",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("SAVINGS_ACCOUNT", "Savings Account Transfer"),
                            ("CHEQUE", "Cheque"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference (e.g., mobile money transaction ID)",
                        max_length=100,
                        null=True,
                        verbose_name="Reference Number",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Receipt Number",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "is_reversed",
                    models.BooleanField(default=False, verbose_name="Is Reversed"),
                ),
                (
                    "reversal_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Reversal Reason"
                    ),
                ),
                (
                    "reversal_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reversal Date"
                    ),
                ),
                (
                    "reversed_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who reversed the payment",
                        max_length=50,
                        null=True,
                        verbose_name="Reversed By",
                    ),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Financial period when payment was made",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_payments",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        help_text="Loan this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="loans.loan",
                    ),
                ),
                (
                    "payment_method_ref",
                    models.ForeignKey(
                        blank=True,
                        help_text="Payment method configuration reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_payments",
                        to="core.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Payment",
                "verbose_name_plural": "Loan Payments",
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["loan", "payment_date"],
                        name="loans_loanp_loan_id_7ae122_idx",
                    ),
                    models.Index(
                        fields=["payment_method", "payment_date"],
                        name="loans_loanp_payment_d7738a_idx",
                    ),
                    models.Index(
                        fields=["is_reversed"], name="loans_loanp_is_reve_c40e75_idx"
                    ),
                    models.Index(
                        fields=["payment_number"], name="loans_loanp_payment_b202d5_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["status", "application_date"],
                name="loans_loana_status_ff64d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["member", "status"], name="loans_loana_member__58930b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["loan_product", "status"], name="loans_loana_loan_pr_faad20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["application_number"], name="loans_loana_applica_d0394f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["status", "disbursement_date"],
                name="loans_loan_status_3eb1cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["member", "status"], name="loans_loan_member__b85b77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["loan_product", "status"], name="loans_loan_loan_pr_63a4bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["days_in_arrears"], name="loans_loan_days_in_68500a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["loan_number"], name="loans_loan_loan_nu_9c0f1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["next_payment_date"], name="loans_loan_next_pa_7a696a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanschedule",
            index=models.Index(
                fields=["due_date", "status"], name="loans_loans_due_dat_2e7162_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanschedule",
            index=models.Index(
                fields=["status", "days_late"], name="loans_loans_status_424f55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanschedule",
            index=models.Index(
                fields=["loan", "status"], name="loans_loans_loan_id_2fb823_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="loanschedule",
            unique_together={("loan", "installment_number")},
        ),
    ]
