# Generated by Django 5.2 on 2025-12-29 14:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareCapital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/description of this share capital configuration",
                        max_length=100,
                        verbose_name="Share Capital Name",
                    ),
                ),
                (
                    "share_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per share",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Share Price",
                    ),
                ),
                (
                    "minimum_shares",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum shares a member must own",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Minimum Shares",
                    ),
                ),
                (
                    "maximum_shares",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum shares a member can own (blank for no limit)",
                        null=True,
                        verbose_name="Maximum Shares",
                    ),
                ),
                (
                    "allow_fractional_shares",
                    models.BooleanField(
                        default=False,
                        help_text="Whether fractional shares are allowed",
                        verbose_name="Allow Fractional Shares",
                    ),
                ),
                (
                    "minimum_purchase_shares",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum shares per purchase transaction",
                        verbose_name="Minimum Purchase Shares",
                    ),
                ),
                (
                    "maximum_purchase_shares",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum shares per purchase transaction",
                        null=True,
                        verbose_name="Maximum Purchase Shares",
                    ),
                ),
                (
                    "allow_redemption",
                    models.BooleanField(
                        default=True,
                        help_text="Whether members can redeem (sell back) shares",
                        verbose_name="Allow Redemption",
                    ),
                ),
                (
                    "redemption_notice_period_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Notice period required before share redemption",
                        verbose_name="Redemption Notice Period (Days)",
                    ),
                ),
                (
                    "early_redemption_penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Penalty for early redemption as percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Early Redemption Penalty (%)",
                    ),
                ),
                (
                    "minimum_holding_period_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum days shares must be held before redemption",
                        verbose_name="Minimum Holding Period (Days)",
                    ),
                ),
                (
                    "allow_transfers",
                    models.BooleanField(
                        default=True,
                        help_text="Whether share transfers between members are allowed",
                        verbose_name="Allow Transfers",
                    ),
                ),
                (
                    "transfer_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed fee for share transfers",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Transfer Fee",
                    ),
                ),
                (
                    "transfer_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Transfer fee as percentage of transaction value",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Transfer Fee (%)",
                    ),
                ),
                (
                    "require_transfer_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Whether transfers require approval",
                        verbose_name="Require Transfer Approval",
                    ),
                ),
                (
                    "issue_certificates",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to issue share certificates",
                        verbose_name="Issue Certificates",
                    ),
                ),
                (
                    "certificate_prefix",
                    models.CharField(
                        default="SC",
                        help_text="Prefix for certificate numbers",
                        max_length=10,
                        verbose_name="Certificate Prefix",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this share capital configuration is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when this configuration becomes effective",
                        verbose_name="Effective Date",
                    ),
                ),
                (
                    "gl_account_code",
                    models.CharField(
                        blank=True,
                        help_text="General Ledger account code for share capital",
                        max_length=20,
                        null=True,
                        verbose_name="GL Account Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Share Capital",
                "verbose_name_plural": "Share Capital",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "effective_date"],
                        name="shares_shar_is_acti_bf8b48_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShareTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        editable=False,
                        help_text="Unique transaction number",
                        max_length=20,
                        unique=True,
                        verbose_name="Transaction Number",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("BUY", "Purchase"),
                            ("SELL", "Sale/Redemption"),
                            ("TRANSFER_OUT", "Transfer Out"),
                            ("TRANSFER_IN", "Transfer In"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        db_index=True,
                        max_length=15,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Transaction Date",
                    ),
                ),
                (
                    "shares_count",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Number of shares in this transaction",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Number of Shares",
                    ),
                ),
                (
                    "price_per_share",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per share for this transaction",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Price Per Share",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total transaction amount",
                        max_digits=15,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference (e.g., receipt number, transaction ID)",
                        max_length=100,
                        null=True,
                        verbose_name="Reference Number",
                    ),
                ),
                (
                    "transfer_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fee charged for transfer",
                        max_digits=10,
                        verbose_name="Transfer Fee",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approval_required",
                    models.BooleanField(
                        default=False, verbose_name="Approval Required"
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved Date"
                    ),
                ),
                (
                    "approved_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who approved the transaction",
                        max_length=50,
                        null=True,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "is_reversed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Reversed"
                    ),
                ),
                (
                    "reversal_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Reversal Reason"
                    ),
                ),
                (
                    "reversal_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reversal Date"
                    ),
                ),
                (
                    "reversed_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who reversed the transaction",
                        max_length=50,
                        null=True,
                        verbose_name="Reversed By",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Financial period when transaction occurred",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="share_transactions",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "linked_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked transaction (e.g., corresponding transfer)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_transactions",
                        to="shares.sharetransaction",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member involved in this transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_transactions",
                        to="members.member",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        help_text="Payment method used",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_transactions",
                        to="core.paymentmethod",
                    ),
                ),
                (
                    "reversal_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reversal transaction reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_transaction",
                        to="shares.sharetransaction",
                    ),
                ),
                (
                    "share_capital",
                    models.ForeignKey(
                        help_text="Share capital configuration at time of transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shares.sharecapital",
                    ),
                ),
                (
                    "transfer_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Member transferring shares (for transfers)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_transfers_out",
                        to="members.member",
                    ),
                ),
                (
                    "transfer_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Member receiving shares (for transfers)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_transfers_in",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Transaction",
                "verbose_name_plural": "Share Transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="ShareTransferRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        editable=False,
                        help_text="Unique request number",
                        max_length=20,
                        unique=True,
                        verbose_name="Request Number",
                    ),
                ),
                (
                    "shares_count",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Number of shares to transfer",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Number of Shares",
                    ),
                ),
                (
                    "share_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Agreed price per share",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Share Price",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total transfer value",
                        max_digits=15,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "transfer_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fee for this transfer",
                        max_digits=10,
                        verbose_name="Transfer Fee",
                    ),
                ),
                (
                    "request_date",
                    models.DateField(auto_now_add=True, verbose_name="Request Date"),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completion Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who approved the transfer",
                        max_length=50,
                        null=True,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Rejection Reason"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for requesting transfer",
                        verbose_name="Reason for Transfer",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "from_member",
                    models.ForeignKey(
                        help_text="Member transferring shares",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_transfers_from",
                        to="members.member",
                    ),
                ),
                (
                    "to_member",
                    models.ForeignKey(
                        help_text="Member receiving shares",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_transfers_to",
                        to="members.member",
                    ),
                ),
                (
                    "transfer_in_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transfer in transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_in_requests",
                        to="shares.sharetransaction",
                    ),
                ),
                (
                    "transfer_out_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transfer out transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_out_requests",
                        to="shares.sharetransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Transfer Request",
                "verbose_name_plural": "Share Transfer Requests",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="ShareCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        editable=False,
                        help_text="Unique certificate number",
                        max_length=20,
                        unique=True,
                        verbose_name="Certificate Number",
                    ),
                ),
                (
                    "shares_count",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Number of shares on this certificate",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Number of Shares",
                    ),
                ),
                (
                    "share_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per share at time of issue",
                        max_digits=12,
                        verbose_name="Share Price",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value of shares on certificate",
                        max_digits=15,
                        verbose_name="Total Value",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        help_text="Date when certificate was issued",
                        verbose_name="Issue Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CANCELLED", "Cancelled"),
                            ("TRANSFERRED", "Transferred"),
                            ("LOST", "Lost"),
                            ("REISSUED", "Reissued"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this certificate is currently valid",
                        verbose_name="Is Valid",
                    ),
                ),
                (
                    "cancellation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Cancellation Date"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Cancellation Reason"
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        help_text="Digital copy of the certificate",
                        null=True,
                        upload_to="share_certificates/",
                        verbose_name="Certificate File",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member who owns these shares",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_certificates",
                        to="members.member",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Certificate that replaced this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="shares.sharecertificate",
                    ),
                ),
                (
                    "share_capital",
                    models.ForeignKey(
                        help_text="Share capital configuration",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shares.sharecapital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Certificate",
                "verbose_name_plural": "Share Certificates",
                "ordering": ["-issue_date"],
                "indexes": [
                    models.Index(
                        fields=["member", "status"],
                        name="shares_shar_member__e42cca_idx",
                    ),
                    models.Index(
                        fields=["certificate_number"],
                        name="shares_shar_certifi_4e5c5b_idx",
                    ),
                    models.Index(
                        fields=["status", "is_valid"],
                        name="shares_shar_status_a5fd5a_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sharetransaction",
            index=models.Index(
                fields=["member", "transaction_type", "status"],
                name="shares_shar_member__ec9baf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sharetransaction",
            index=models.Index(
                fields=["transaction_date", "status"],
                name="shares_shar_transac_614ea1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sharetransaction",
            index=models.Index(
                fields=["status", "is_reversed"], name="shares_shar_status_e43e31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharetransaction",
            index=models.Index(
                fields=["transaction_number"], name="shares_shar_transac_c92c1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharetransferrequest",
            index=models.Index(
                fields=["from_member", "status"], name="shares_shar_from_me_c1f201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharetransferrequest",
            index=models.Index(
                fields=["to_member", "status"], name="shares_shar_to_memb_5610a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharetransferrequest",
            index=models.Index(
                fields=["status", "request_date"], name="shares_shar_status_fa7a88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharetransferrequest",
            index=models.Index(
                fields=["request_number"], name="shares_shar_request_99ef81_idx"
            ),
        ),
    ]
