# Generated by Django 5.2 on 2025-12-29 07:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("members", "0001_initial"),
        ("savings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DividendPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the dividend period (e.g., 'FY 2024 Dividends')",
                        max_length=100,
                        verbose_name="Period Name",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Start date of the dividend period",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="End date of the dividend period",
                        verbose_name="End Date",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(
                        help_text="Date for determining eligible shareholders",
                        verbose_name="Record Date",
                    ),
                ),
                (
                    "declaration_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when dividend was declared",
                        null=True,
                        verbose_name="Declaration Date",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when dividend will be/was paid",
                        null=True,
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "total_dividend_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount available for dividend distribution",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Total Dividend Amount",
                    ),
                ),
                (
                    "dividend_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dividend rate in percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Dividend Rate (%)",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("FLAT_RATE", "Flat Rate"),
                            ("WEIGHTED_AVERAGE", "Weighted Average"),
                            ("TIERED", "Tiered By Share Amount"),
                            ("PRO_RATA", "Pro Rata Distribution"),
                        ],
                        default="FLAT_RATE",
                        max_length=20,
                        verbose_name="Calculation Method",
                    ),
                ),
                (
                    "withholding_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Withholding tax rate to apply",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Withholding Tax Rate (%)",
                    ),
                ),
                (
                    "apply_withholding_tax",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to apply withholding tax on dividends",
                        verbose_name="Apply Withholding Tax",
                    ),
                ),
                (
                    "default_disbursement_method",
                    models.CharField(
                        choices=[
                            ("SAVINGS_ACCOUNT", "Savings Account"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CASH", "Cash"),
                        ],
                        default="SAVINGS_ACCOUNT",
                        max_length=20,
                        verbose_name="Default Disbursement Method",
                    ),
                ),
                (
                    "allow_member_choice",
                    models.BooleanField(
                        default=False,
                        help_text="Allow members to choose disbursement method",
                        verbose_name="Allow Member Choice",
                    ),
                ),
                (
                    "minimum_payout_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum amount for dividend payout",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Minimum Payout Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("CALCULATING", "Calculating"),
                            ("CALCULATED", "Calculated"),
                            ("APPROVED", "Approved"),
                            ("DISBURSING", "Disbursing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Is Approved"),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
                (
                    "approved_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who approved the dividend period",
                        max_length=50,
                        null=True,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "total_members",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of members eligible for dividends",
                        verbose_name="Total Members",
                    ),
                ),
                (
                    "total_shares",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of shares in the period",
                        verbose_name="Total Shares",
                    ),
                ),
                (
                    "total_shares_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value of all shares",
                        max_digits=15,
                        verbose_name="Total Shares Value",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        help_text="Financial period this dividend relates to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dividend_periods",
                        to="core.fiscalperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dividend Period",
                "verbose_name_plural": "Dividend Periods",
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="DividendDisbursement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateField(
                        help_text="Date when disbursement was/will be made",
                        verbose_name="Disbursement Date",
                    ),
                ),
                (
                    "disbursement_method",
                    models.CharField(
                        choices=[
                            ("SAVINGS_ACCOUNT", "Savings Account"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CASH", "Cash"),
                        ],
                        max_length=20,
                        verbose_name="Disbursement Method",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="Unique batch identifier",
                        max_length=50,
                        unique=True,
                        verbose_name="Batch Number",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "total_members",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of members in this batch",
                        verbose_name="Total Members",
                    ),
                ),
                (
                    "processed_members",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of members processed",
                        verbose_name="Processed Members",
                    ),
                ),
                (
                    "successful_members",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of successful payments",
                        verbose_name="Successful Members",
                    ),
                ),
                (
                    "failed_members",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of failed payments",
                        verbose_name="Failed Members",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount to disburse",
                        max_digits=15,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "processed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount successfully processed",
                        max_digits=15,
                        verbose_name="Processed Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Time"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "dividend_period",
                    models.ForeignKey(
                        help_text="Dividend period for this disbursement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursements",
                        to="dividends.dividendperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dividend Disbursement",
                "verbose_name_plural": "Dividend Disbursements",
                "ordering": ["-disbursement_date"],
            },
        ),
        migrations.CreateModel(
            name="DividendPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default preference",
                        verbose_name="Is Default",
                    ),
                ),
                (
                    "preference_method",
                    models.CharField(
                        choices=[
                            ("SAVINGS_ACCOUNT", "Savings Account"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CASH", "Cash"),
                        ],
                        max_length=20,
                        verbose_name="Preference Method",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bank Name"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Bank Account",
                    ),
                ),
                (
                    "bank_branch",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Bank Branch",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "mobile_provider",
                    models.CharField(
                        blank=True,
                        help_text="Mobile money provider (MTN, Airtel, etc.)",
                        max_length=50,
                        null=True,
                        verbose_name="Mobile Provider",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "dividend_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific dividend period (null = default preference)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_preferences",
                        to="dividends.dividendperiod",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member who set this preference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividend_preferences",
                        to="members.member",
                    ),
                ),
                (
                    "savings_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preferred savings account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dividend_preferences",
                        to="savings.savingsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dividend Preference",
                "verbose_name_plural": "Dividend Preferences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DividendRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        help_text="Name of this tier (e.g., 'Bronze', 'Silver', 'Gold')",
                        max_length=100,
                        verbose_name="Tier Name",
                    ),
                ),
                (
                    "min_shares",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum number of shares for this tier",
                        verbose_name="Minimum Shares",
                    ),
                ),
                (
                    "max_shares",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of shares (blank for no limit)",
                        null=True,
                        verbose_name="Maximum Shares",
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum share value for this tier",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Minimum Value",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum share value (blank for no limit)",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Maximum Value",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dividend rate for this tier in percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Rate (%)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "dividend_period",
                    models.ForeignKey(
                        help_text="Dividend period this rate applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividend_rates",
                        to="dividends.dividendperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dividend Rate",
                "verbose_name_plural": "Dividend Rates",
                "ordering": ["dividend_period", "min_shares", "min_value"],
            },
        ),
        migrations.CreateModel(
            name="MemberDividend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "shares_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of shares owned by member",
                        verbose_name="Number of Shares",
                    ),
                ),
                (
                    "shares_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value of member's shares",
                        max_digits=15,
                        verbose_name="Shares Value",
                    ),
                ),
                (
                    "gross_dividend",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Dividend before tax",
                        max_digits=12,
                        verbose_name="Gross Dividend",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Withholding tax amount",
                        max_digits=12,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "net_dividend",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Dividend after tax",
                        max_digits=12,
                        verbose_name="Net Dividend",
                    ),
                ),
                (
                    "applied_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Dividend rate applied to this member",
                        max_digits=5,
                        verbose_name="Applied Rate (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CALCULATED", "Calculated"),
                            ("APPROVED", "Approved"),
                            ("PROCESSING", "Processing Payment"),
                            ("PAID", "Paid"),
                            ("FAILED", "Payment Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="CALCULATED",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "disbursement_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAVINGS_ACCOUNT", "Savings Account"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CASH", "Cash"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Disbursement Method",
                    ),
                ),
                (
                    "disbursement_reference",
                    models.CharField(
                        blank=True,
                        help_text="External reference for disbursement",
                        max_length=100,
                        null=True,
                        verbose_name="Disbursement Reference",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Payment Reference",
                    ),
                ),
                (
                    "payment_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Payment Notes"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Failure Reason"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Retry Count"),
                ),
                (
                    "disbursement_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Savings account for disbursement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dividend_disbursements",
                        to="savings.savingsaccount",
                    ),
                ),
                (
                    "dividend_period",
                    models.ForeignKey(
                        help_text="Dividend period this dividend belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_dividends",
                        to="dividends.dividendperiod",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member receiving the dividend",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividends",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Dividend",
                "verbose_name_plural": "Member Dividends",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DividendPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        help_text="Date when payment was made",
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Payment reference number",
                        max_length=100,
                        null=True,
                        verbose_name="Payment Reference",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Receipt Number",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bank Name"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Bank Account",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="External transaction ID",
                        max_length=100,
                        null=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Transaction Date"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Failure Reason"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Retry Count"),
                ),
                (
                    "last_retry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Retry Date"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "disbursement",
                    models.ForeignKey(
                        help_text="Disbursement batch this payment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="dividends.dividenddisbursement",
                    ),
                ),
                (
                    "savings_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Savings account payment was made to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dividend_payments",
                        to="savings.savingsaccount",
                    ),
                ),
                (
                    "member_dividend",
                    models.ForeignKey(
                        help_text="Member dividend this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="dividends.memberdividend",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dividend Payment",
                "verbose_name_plural": "Dividend Payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="dividendperiod",
            index=models.Index(
                fields=["status", "end_date"], name="dividends_d_status_a1302f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividendperiod",
            index=models.Index(
                fields=["financial_period"], name="dividends_d_financi_c592f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividendperiod",
            index=models.Index(
                fields=["record_date"], name="dividends_d_record__b08386_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividenddisbursement",
            index=models.Index(
                fields=["dividend_period", "status"],
                name="dividends_d_dividen_25000c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dividenddisbursement",
            index=models.Index(
                fields=["batch_number"], name="dividends_d_batch_n_ddab26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividenddisbursement",
            index=models.Index(
                fields=["disbursement_date"], name="dividends_d_disburs_883881_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividenddisbursement",
            index=models.Index(fields=["status"], name="dividends_d_status_3fa8bd_idx"),
        ),
        migrations.AddIndex(
            model_name="dividendpreference",
            index=models.Index(
                fields=["member", "is_default"], name="dividends_d_member__40472a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividendpreference",
            index=models.Index(
                fields=["member", "dividend_period"],
                name="dividends_d_member__891460_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dividendpreference",
            unique_together={("member", "dividend_period")},
        ),
        migrations.AddIndex(
            model_name="dividendrate",
            index=models.Index(
                fields=["dividend_period", "is_active"],
                name="dividends_d_dividen_c1fc7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memberdividend",
            index=models.Index(
                fields=["dividend_period", "status"],
                name="dividends_m_dividen_4a3a78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memberdividend",
            index=models.Index(
                fields=["member", "status"], name="dividends_m_member__64fd7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberdividend",
            index=models.Index(
                fields=["status", "payment_date"], name="dividends_m_status_27bf1d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="memberdividend",
            unique_together={("dividend_period", "member")},
        ),
        migrations.AddIndex(
            model_name="dividendpayment",
            index=models.Index(
                fields=["status", "payment_date"], name="dividends_d_status_81c403_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividendpayment",
            index=models.Index(
                fields=["disbursement", "status"], name="dividends_d_disburs_169e1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividendpayment",
            index=models.Index(
                fields=["member_dividend"], name="dividends_d_member__f04768_idx"
            ),
        ),
    ]
